application: wiki-eats
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /.*
  script: wikieats.application

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: 1.1.7