application: wiki-eats
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: wikieats.application

libraries:
- name: webapp2
  version: latest
- name: PIL
  version: 1.1.7